services:
  drone-srcb:
    build: .
    environment:
      TG_OWNER_ID: $TG_OWNER_ID  
      TG_BOT_TOKEN: $TG_BOT_TOKEN  
      REMOVE_BG_API: $REMOVE_BG_API 
      PMGUARD_ENABLED: $PMGUARD_ENABLED
      DB_URL: $DB_URL
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
